### PR TITLE
Updated journal-week-2.md

### PR DESCRIPTION
**Pull request by jeffworley**
Removed last of outline and rough draft organization markers and proofread to ensure it is decipherable

### CODE REVIEW

**Comment by jmcreasman** [comment]
Awesome job, I liked how you wrote it like a conversation between you and the reader :+1:

**Comment by rosalsm** [comment]
I like your conversation with yourself. I do it too a lot :+1:

**Comment by ShayHall** [comment]
:+1: I like the casual tone of your writing.  It makes reading about complex, abstract ideas more palatable.  I believe "thingamajigger " is the proper spelling. thingamajigger Other than that, good job.

**Comment by s4dmw** [comment]
good work. i like your use of examples to show that you're really getting the concept!!!!!!!111@!

:+1:

**Pull request merged**
