### PR TITLE
journal-week-5

### PR DESCRIPTION
**Pull request by jeffworley**

### CODE REVIEW

**Comment by jeremyrist** [comment]
:+1: lookin' good!

**Comment by s4dmw** [comment]
journal - pretty much agree with everything you wrote...and i hate when that happens :+1: 
resource - good writeup, MDN is a great resource :+1: 
tutorial - good stuff about the mysterious git - looking forward to the finished product :+1: 
- [x] :+1:  for good measure

**Comment by s4dmw** [comment]
useful and timely tutorial for both us considering we both have some merge conflicts on our journal PR's...nice work :+1:

**Comment by ShayHall** [comment]
Looks good.  Entertaining reflect, as usual.  Thorough tutorial and resource journal.  Thumbs for all! :+1: :+1: :+1:

**Pull request merged**
