### PR TITLE
journal-week-3-pt-3

### PR DESCRIPTION
**Pull request by jeffworley**

### CODE REVIEW

**Comment by s4dmw** [comment]
journal - eloquent as usual! I'm in agreement that responsive design is very important these days.

tutorial - it's shaping up nicely. i look forward to seeing the finished product.

:+1:

**Comment by Ricecoder** [comment]
Very good! Both your journal and tutorial were very informative and funny. I really enjoyed reading them! :+1:

**Comment by jeremyrist** [comment]
:+1: Thanks JR, always helpful and informative

**Comment by jmcreasman** [comment]
Coming together! Just keep swimming :+1:

**Comment by ericquayson** [comment]
:+1: Nice journal! It was comical and informative.

**Pull request merged**
